server {
    listen 8090;
    server_name _;

    set $video_secret "__NGINX_VIDEO_SECRET__";

    location /video/ {
        secure_link $arg_md5,$arg_expires;
        secure_link_md5 "$video_secret$uri$arg_expires";

        if ($secure_link = "") { return 403; }
        if ($secure_link = "0") { return 410; }

        alias /uploads/;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        add_header Accept-Ranges bytes always;
    }
}
